### ISSUE TITLE
Dates `testParseFailureA` is failing

### ISSUE THREAD

**Issue by patdel0** [dxw/php-missing#24]
The test is expecting an error to be returned but `parse('2012-06-006 19:00')` is returning an object for the timestamp `1338422400`.

Currently, it is not returning either an error or the expected timestamp of 1339009200.

https://github.com/dxw/php-missing/blob/172d0a2386645192f1824cdc23f88a66d2fe04cb/tests/dates_test.php#L49-L53

**Comment by snim2** [comment]
What is it returning?

**Comment by patdel0** [comment]
It's returning this:
```
..F....                                                             7 / 7 (100%)

Time: 16 ms, Memory: 4.00 MB

There was 1 failure:

1) DatesTest::testParseFailureA
Failed asserting that false is true.
```

**Comment by snim2** [comment]
Ah right, but I mean if you print out the value and type of `$result`, what do you get?

**Comment by patdel0** [comment]
It's returning an object, containing `value: 1338422400`

![Screenshot 2023-01-13 at 09 55 24](https://user-images.githubusercontent.com/53922624/212291644-1340850e-fd28-4f0c-8edd-fcdbccc3d23e.png)

**Comment by snim2** [comment]
> It's returning an object, containing `value: 1338422400`
> 
> ![Screenshot 2023-01-13 at 09 55 24](https://user-images.githubusercontent.com/53922624/212291644-1340850e-fd28-4f0c-8edd-fcdbccc3d23e.png)

I think that value is a reference to the object, not an actual value. The `Ok` needs to be unwrapped to see what's inside it properly (so easiest to print something to STDOUT,  think)

**Comment by patdel0** [comment]
I'm sorry @snim2, I don't understand what you're asking for.

```
var_dump($result): 
object(Dxw\Result\Ok)#370 (1) {
  ["value":"Dxw\Result\Ok":private]=>
  int(1338422400)
}

print($result->unwrap): 
1338422400
```

Are we not expecting the return of the call `parse('2012-06-006 19:00')` to be an object from `Dxw\Result\Err`?

**Comment by RobjS** [comment]
I had this same issue when running the tests locally, but not when they ran in CI, which makes me think it's either a php config issue, or possibly a timezone thing, with the way we were using `strptime()`. Anyway, the refactoring I had to do for PHP8 compatibility in `v2.0.0` seems to have resolved it, as we're no longer using that function. So I'll close this, but @patdel0 please re-open if you still see the issue!
